### ISSUE TITLE
"Running" but nothing writing

### ISSUE THREAD

**Issue by PaulBernert** [PaulBernert/gdp-shares#1]
@ianmkenney 

When I try to run the analysistools from the GDP-Shares repository, it appears to run the python script (at least 90% of the time), but no folders or files are being written to my computer. The 10% of the time it fails to even run, it says that there is no file called gdp_shares.csv even though there definitely is!
I've tried running it through anaconda's python.exe and jupyter but had no luck with either. I'm pretty sure I'm running it incorrectly, perhaps you can show/tell me how to run a python script correctly haha.

Issues:
- [x] Not recognizing gdp_shares.csv when running analysistools.py
- [x] Incorrectly running python script?

I hope you can help! Everything I'm using can be found in this repository.

**Comment by ianmkenney** [comment]
@PaulBernert is this the same file that was used in the other project?

**Comment by PaulBernert** [comment]
Nope, this file is formatted very similarly, but is a different data set. The old one was called employment_shares.csv (or something similar to that) while this one is gdp_shares.csv. The data set can be found on this repository. Thanks for looking into this!

**Comment by ianmkenney** [comment]
Sorry I mean the analysis tools? When you get a failed run, what is the output of `pwd` and `ls` in the terminal.

**Comment by PaulBernert** [comment]
PaulB@Desktop-3DVTT90 MINGW64 ~projects/gdp-shares (master)
$ pwd
/c/Users/PaulB/projects/gdp-shares

PaulB@Desktop-3DVTT90 MINGW64 ~projects/gdp-shares (master)
$ ls
analysistools.py data/ gdp_shares.csv munge.ipynb README.rst

**Comment by ianmkenney** [comment]
I see that in `gdp_shares.csv` you have United States at the top of the file, do you want that?

**Comment by PaulBernert** [comment]
Yep! I would like to keep that if possible. If it's causing issues then we can drop it though.

**Comment by ianmkenney** [comment]
How do you want to deal with all of the empty entries? Set them to some value?

**Comment by PaulBernert** [comment]
Like blank cells, or (D)s and (Ts)? There shouldn't be any Ds or Ts, but if there are they should definitely be zeroes. Any blank cells can just be zero as well. I'm just realizing now that I forgot to "clean up" the original data set. =P

**Comment by ianmkenney** [comment]
try the changes add in the new commit 10c42a50dbcc383aca187b7566d5f6c1f13c1f5e

**Comment by ianmkenney** [comment]
@PaulBernert The r values are very close to each other, is this right?

**Comment by PaulBernert** [comment]
There are quite a few more values than the last data set (which is why there are also a lot more values being excluded). Perhaps I should try to find a new way to test the similarity between the data sets? This doesn't seem like a very difficult test, so surely there's a easy way to test the similarity between two sets of data somewhere..

Also, I put up my analysistools.py. Hopefully I was able to make all the changes correctly! Thanks so much!

**Comment by ianmkenney** [comment]
You pulled what I commited right?

**Comment by PaulBernert** [comment]
Nope, I looked at the changes you made, made them myself and then commited what I wrote. Looks like I over-wrote your stuff on accident. Sorry! In addition, it looks like I still have the tab error:

state = get_state(z,year,excludes=exc,reference=90) # Gets information for arbitrary state 'z' ^ TabError: inconsistent use of tabs and spaces in indentation.

I'll fix it. God I suck at this  =P

**Comment by ianmkenney** [comment]
Yeah so the changes I made were already part of the codebase. Just use those next time! 

Remember you should use 4 spaces rather than tabs. Which text editor are you using to edit your files? You can set the default TAB/spaces in most editors.

**Comment by PaulBernert** [comment]
I'm using vim, and if you're already tabbed out and press enter, the next line will be exactly how you want it and keep things consistent. I for some reason went through about half the .py file and chose to put in my own tabs and spaces everywhere making it completely inconsistent. I tried to go back and make everything the same but I guess I missed those few spots haha. It should be good now though; going to give it a test run. Fingers crossed!

**Comment by PaulBernert** [comment]
...and you got it to run?

PaulB@DESKTOP-3DVTT90 MINGW64 ~/projects/gdp-shares (master)
$ python analysistools.py
Traceback (most recent call last):
  File "analysistools.py", line 61, in <module>
    compare_to_state(stat,state_list)
  File "analysistools.py", line 44, in compare_to_state
    s_info = get_state(s,year,excludes=exc,reference=90) # 's'-specific information
  File "analysistools.py", line 18, in get_state
    mod = int((data.ix[(data['GeoName'] == state) & (data['LineCode'] == str(reference))][year]).iloc[0]) # Population at reference line code
  File "C:\Users\PaulB\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1286, in __getitem__
    return self._getitem_axis(key, axis=0)
  File "C:\Users\PaulB\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1573, in _getitem_axis
    self._is_valid_integer(key, axis)
  File "C:\Users\PaulB\Anaconda3\lib\site-packages\pandas\core\indexing.py", line 1487, in _is_valid_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds

PaulB@DESKTOP-3DVTT90 MINGW64 ~/projects/gdp-shares (master)
$

I want to die :(

**Comment by ianmkenney** [comment]
`git checkout 10c42a50dbcc383aca187b7566d5f6c1f13c1f5e` then run it again. This will go back to my code

**Comment by PaulBernert** [comment]
PaulB@DESKTOP-3DVTT90 MINGW64 ~/projects/gdp-shares (master)
$ git checkout 10c42a50dbcc383aca187b7566d5f6c1f13c1f5e
fatal: reference is not a tree: 10c42a50dbcc383aca187b7566d5f6c1f13c1f5e

PaulB@DESKTOP-3DVTT90 MINGW64 ~/projects/gdp-shares (master)
$

thank you for being patient with me lol

**Comment by PaulBernert** [comment]
it didn't paste the whole checkout there, but it did in terminal. not sure why it only pasted part of it here

**Comment by ianmkenney** [comment]
You need to put it in \` \` so it realizes it's either code or commands

**Comment by ianmkenney** [comment]
Run `git pull origin master` and then try using the checkout again. It's because you are using the file uploader

**Comment by PaulBernert** [comment]
HOLY TITS ITS WORKING

**Comment by PaulBernert** [comment]
IAN YOU ARE THE MVP <3 <3 <3

**Comment by ianmkenney** [comment]
Awesome dude, glad I could help! Feel free to ask more questions if you need help

**Comment by PaulBernert** [comment]
wait, last thing. It looks like it only did it for 2015 for me. did it do all of them for you?

**Comment by ianmkenney** [comment]
I found there error but it will take a few minutes to patch up. Please never use the file uploader :'( it is the worst feature on this site

**Comment by PaulBernert** [comment]
okie dokie! I need to get used to the git remote then, because for some reason I feel like I do something wrong whenever I try to use it. But I should learn how to use it rather than try to avoid it.

Even though it took me all day and I didn't get much done, I still feel like I've learned a lot about this stuff by just trying stuff on my own. Thanks for the guidance in the end though! ^.^

**Comment by ianmkenney** [comment]
Of course! I understand that it's a lot to take in.

`git pull -f origin master` and try again!

**Comment by PaulBernert** [comment]
you are a god among men! what did you need to change?

**Comment by ianmkenney** [comment]
There were some issues with the tabs still. Do not change any code right now. I need to fix something else that has been driving me crazy. You can see specific changes by clicking the 'commits' tab on the main project page.

**Comment by ianmkenney** [comment]
Alright, there you go. This is much nicer. 

run `rm -r data` and then rerun the script
